# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87216c2fd8577cca916e578da7e36c0f8a6838b059ec9277ed7bbabf040d8a61945b744daa243b3f3db1ff0f4ccacabf6a2ac9d9d882d1bee3f5ec29443b23df
  stripe_publishable_key: pk_test_awMeepBpDpqFp36WzV2YYe16
  stripe_secret_key: sk_test_x3MP7h6RPyPFyht30KTzSpsb
test:
  secret_key_base: a91aac626af87008321dcb444c08faf2af44bbf92f554b4305ff0653572f3711fe2a9e2bd8c4eee561df7bf1b88ef2411199d8a67631784a70f9e9bf45edbec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']